# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.TextField(null=True)),
                ('job_title', models.TextField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('job_date', models.DateField(null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=1000)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Hire_Review')),
            ],
        ),
        migrations.CreateModel(
            name='Hires_H1B',
            fields=[
                ('source', models.TextField(null=True)),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('employer_name', models.TextField(null=True)),
                ('employer_address1', models.TextField(null=True)),
                ('employer_address2', models.TextField(null=True)),
                ('employer_city', models.TextField(null=True)),
                ('employer_state', models.TextField(null=True)),
                ('employer_postal_code', models.TextField(null=True)),
                ('job_title', models.TextField(null=True)),
                ('wage_from_1', models.FloatField(null=True)),
                ('wage_to_1', models.FloatField(null=True)),
                ('rate_unit_1', models.TextField(null=True)),
                ('std_title', models.TextField(null=True)),
                ('submitted_date', models.DateField(null=True)),
                ('case_number', models.TextField(null=True)),
                ('employment_start_date', models.DateField(null=True)),
                ('pw_1', models.FloatField(null=True)),
                ('pw_unit_1', models.TextField(null=True)),
                ('work_location_city1', models.TextField(null=True)),
                ('work_location_state1', models.TextField(null=True)),
                ('wage_from_2', models.FloatField(null=True)),
                ('wage_to_2', models.FloatField(null=True)),
                ('rate_unit_2', models.TextField(null=True)),
                ('pw_2', models.FloatField(null=True)),
                ('pw_unit_2', models.TextField(null=True)),
                ('work_location_city2', models.TextField(null=True)),
                ('work_location_state2', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hires_Perm',
            fields=[
                ('source', models.TextField(null=True)),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('employer_name', models.TextField(null=True)),
                ('employer_address1', models.TextField(null=True)),
                ('employer_address2', models.TextField(null=True)),
                ('employer_city', models.TextField(null=True)),
                ('employer_state', models.TextField(null=True)),
                ('employer_postal_code', models.TextField(null=True)),
                ('job_title', models.TextField(null=True)),
                ('wage_from_1', models.FloatField(null=True)),
                ('wage_to_1', models.FloatField(null=True)),
                ('rate_unit_1', models.TextField(null=True)),
                ('std_title', models.TextField(null=True)),
                ('decision_date', models.DateField(null=True)),
                ('case_number', models.TextField(null=True)),
                ('pw_1', models.FloatField(null=True)),
                ('pw_unit_1', models.TextField(null=True)),
                ('work_location_city1', models.TextField(null=True)),
                ('work_location_state1', models.TextField(null=True)),
                ('job_info_education', models.TextField(null=True)),
                ('job_info_major', models.TextField(null=True)),
                ('country_of_citizenship', models.TextField(null=True)),
                ('class_of_admission', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
