# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oflcperm',
            name='case_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='case_received_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='case_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='class_of_admission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='decision_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_address_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_address_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_num_employees',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_postal_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='employer_yr_estab',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='job_info_education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='job_info_job_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='job_info_major',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='pw_amount_9089',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='pw_unit_of_pay_9089',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='wage_offer_from_9089',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='wage_offer_to_9089',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='wage_offer_unit_of_pay_9089',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
