# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]
    operations = [
        migrations.RunSQL(
            ('CREATE UNIQUE INDEX UIdx_h1b ON reviews_hires_h1b '
                '(coalesce(employment_confirmed,\'False\')'
                ',coalesce(employer_name,\'\')'
                ',coalesce(employer_address1,\'\')'
                ',coalesce(employer_address2,\'\')'
                ',coalesce(employer_city,\'\')'
                ',coalesce(employer_state,\'\')'
                ',coalesce(employer_postal_code,\'\')'
                ',coalesce(job_title,\'\')'
                ',coalesce(wage_from_1,0.0)'
                ',coalesce(wage_to_1,0.0)'
                ',coalesce(rate_unit_1,\'\')'
                ',coalesce(std_title,\'\')'

                ',coalesce(submitted_date,\'1900-01-01\')'
                ',coalesce(case_number,\'\')'
                ',coalesce(employment_start_date,\'1900-01-01\')'
                ',coalesce(pw_1,0.0)'
                ',coalesce(pw_unit_1,\'\')'
                ',coalesce(work_location_city1,\'\')'
                ',coalesce(work_location_state1,\'\')'
                ',coalesce(wage_from_2,0.0)'
                ',coalesce(wage_to_2,0.0)'
                ',coalesce(rate_unit_2,\'\')'
                ',coalesce(pw_2,0.0)'
                ',coalesce(pw_unit_2,\'\')'
                ',coalesce(work_location_city2,\'\')'
                ',coalesce(work_location_state2,\'\'));'

                'CREATE UNIQUE INDEX UIdx_perm ON reviews_hires_perm '
                '(coalesce(employment_confirmed,\'False\')'
                ',coalesce(employer_name,\'\')'
                ',coalesce(employer_address1,\'\')'
                ',coalesce(employer_address2,\'\')'
                ',coalesce(employer_city,\'\')'
                ',coalesce(employer_state,\'\')'
                ',coalesce(employer_postal_code,\'\')'
                ',coalesce(job_title,\'\')'
                ',coalesce(wage_from_1,0.0)'
                ',coalesce(wage_to_1,0.0)'
                ',coalesce(rate_unit_1,\'\')'
                ',coalesce(std_title,\'\')'

                ',coalesce(decision_date, \'1900-01-01\')'
                ',coalesce(case_number,\'\')'
                ',coalesce(pw_1, 0.0)'
                ',coalesce(pw_unit_1,\'\')'
                ',coalesce(work_location_city1,\'\')'
                ',coalesce(work_location_state1,\'\')'
                ',coalesce(job_info_education,\'\')'
                ',coalesce(job_info_major,\'\')'
                ',coalesce(country_of_citizenship,\'\')'
                ',coalesce(class_of_admission,\'\'));'
                
                'CREATE UNIQUE INDEX UIdx_h2a ON reviews_hires_h2a '
                '(coalesce(employment_confirmed,\'False\')'
                ',coalesce(employer_name,\'\')'
                ',coalesce(employer_address1,\'\')'
                ',coalesce(employer_address2,\'\')'
                ',coalesce(employer_city,\'\')'
                ',coalesce(employer_state,\'\')'
                ',coalesce(employer_postal_code,\'\')'
                ',coalesce(job_title,\'\')'
                ',coalesce(wage_from_1,0.0)'
                ',coalesce(wage_to_1,0.0)'
                ',coalesce(rate_unit_1,\'\')'
                ',coalesce(std_title,\'\')'

                ',coalesce(decision_date, \'1900-01-01\')'
                ',coalesce(case_number,\'\')'
                ',coalesce(work_location_city1,\'\')'
                ',coalesce(work_location_state1,\'\')'
                ',coalesce(employment_start_date, \'1900-01-01\')'
                ',coalesce(employment_end_date, \'1900-01-01\')'
                ',coalesce(certification_begin_date, \'1900-01-01\')'
                ',coalesce(certification_end_date, \'1900-01-01\'));'

                'CREATE UNIQUE INDEX UIdx_h2b ON reviews_hires_h2b '
                '(coalesce(employment_confirmed,\'False\')'
                ',coalesce(employer_name,\'\')'
                ',coalesce(employer_address1,\'\')'
                ',coalesce(employer_address2,\'\')'
                ',coalesce(employer_city,\'\')'
                ',coalesce(employer_state,\'\')'
                ',coalesce(employer_postal_code,\'\')'
                ',coalesce(job_title,\'\')'
                ',coalesce(wage_from_1,0.0)'
                ',coalesce(wage_to_1,0.0)'
                ',coalesce(rate_unit_1,\'\')'
                ',coalesce(std_title,\'\')'

                ',coalesce(decision_date, \'1900-01-01\')'
                ',coalesce(case_number,\'\')'
                ',coalesce(work_location_city1,\'\')'
                ',coalesce(work_location_state1,\'\')'
                ',coalesce(certification_begin_date, \'1900-01-01\')'
                ',coalesce(certification_end_date, \'1900-01-01\')'
                ',coalesce(overtime_rate_from,0.0)'
                ',coalesce(overtime_rate_to,0.0)'
                ',coalesce(pw_1,0.0)'
                ',coalesce(pw_unit_1,\'\')'
                ',coalesce(employment_start_date, \'1900-01-01\')'
                ',coalesce(employment_end_date, \'1900-01-01\')'
                ',coalesce(job_info_education,\'\')'
                ',coalesce(job_info_major,\'\')'
                ',coalesce(job_info_other_education,\'\')'
                ',coalesce(job_info_second_major,\'\'));'
             ), 

            'DROP INDEX UIdx_perm;'
            'DROP INDEX UIdx_h1b;'
            'DROP INDEX UIdx_h2a;'
            'DROP INDEX UIdx_h2b;'
        )
    ]
