# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160325_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oflcperm',
            name='case_received_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='case_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oflcperm',
            name='decision_date',
            field=models.DateField(null=True),
        ),
    ]
