# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160325_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oflch1b',
            unique_together=set([('year', 'case_no')]),
        ),
    ]
