# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20160424_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oflcperm',
            old_name='job_info_job_title',
            new_name='job_title',
        ),
    ]
