# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20160418_2355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oflch1b',
            unique_together=set([]),
        ),
    ]
