# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20160418_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oflch1b',
            unique_together=set([('year', 'case_no', 'case_status', 'employer_name', 'job_title')]),
        ),
    ]
