# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20160419_2303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oflch1b',
            unique_together=set([('year', 'case_no', 'case_status', 'prevailing_wage', 'wage_rate_of_pay_from')]),
        ),
    ]
