# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20160419_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oflch1b',
            name='soc_name',
        ),
    ]
