# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_remove_oflch1b_soc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oflcperm',
            old_name='employer_address_1',
            new_name='employer_address1',
        ),
        migrations.RenameField(
            model_name='oflcperm',
            old_name='employer_address_2',
            new_name='employer_address2',
        ),
    ]
